# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"@\n\x0cNotification\x12\x0c\n\x04type\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x62\x06proto3')



_NOTIFICATION = DESCRIPTOR.message_types_by_name['Notification']
Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:notification.Notification)
  })
_sym_db.RegisterMessage(Notification)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTIFICATION._serialized_start=36
  _NOTIFICATION._serialized_end=100
# @@protoc_insertion_point(module_scope)
